### ISSUE TITLE
split directive is showing blank

### ISSUE THREAD

**Issue by js321** [scahitdemir/ng-split#1]
Hello,

I've installed the Split.Js and ng-split using bower and have configured it. I'm not getting any javascript or Angular errors.

I have used the below sample code but i cannot see anything on the page. any ideas? any help would be much appreciated.

`<split direction="horizontal">
    <split-area size="50">
        <p>Lorem ipsum dolor sit amet...</p>
    </split-area>
    <split-area size="50">
        <p>Sed ut perspiciatis unde omnis iste natus erro...</p>
    </split-area>
</split>`

Thank you

**Comment by dineshnamburi** [comment]
Using ng-transclude in all the split and split-area directives allows it to work.

Example: <split direction="horizontal" ng-transclude><split-area size="50" ng-transclude>...
....

**Comment by dineshnamburi** [comment]
Using ng-transclude in all the split and split-area directives allows it to work.

Example: **`<split direction="horizontal" ng-transclude><split-area size="50" ng-transclude>`**...
....

**Comment by MacGyver98** [comment]
Hi!

Thanks for your time doing this!

I've need to add the ng-transclude to all split-directives.  But the gutter doesn't move...  I see the style property of elements changing them in "ïnspect window", but the gutter and containers don't move.

Any idea???

Have a good day!

Edit:  It looks like a issue with calc() CSS function and use of percentages... I'm looking for parent nodes and their CSS properties.... I'll told you when find an answer

Edit 2:  This is the answer!
[https://stackoverflow.com/questions/1622027/percentage-height-html-5-css](url)

It's necessary wrap our `<split>` with a explicit height element

**Comment by scahitdemir** [comment]
it has been fixed by @icholy
