### ISSUE TITLE
ng-split, ui-router and parent-child states

### ISSUE THREAD

**Issue by MacGyver98** [scahitdemir/ng-split#3]
Hi!

If a I have a vertical split with two areas (20,80), and the second area (80%) has a <ui-view> element, and  inside this another split but horizontal, this one doesn't work propertly.

```
<split direction="vertical">
	<split-area size="20">
        </split>
	<split-area size="80">
		<ui-view>
			<!-- template's html -->
                       <split direction="horizontal">
				<split-area size="20" ng-transclude>
				</split-area>
				<split-area size="80" ng-transclude>
				</split-area>
			</split>
		</ui-view>
	</split-area>
</split>
```

Sorry, found a solution:

```
<ui-view style="height: calc(100%);">
```

ui-view element needs a fixed height, width this tricky css you can set a "fixed" height dynamicly
(sorry my english!)

**Comment by scahitdemir** [comment]
Thank you for your interest. I leave these kinds of improvements up to the user.
